# Generated by Django 5.2.1 on 2025-06-01 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='Contenido')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentarios', to='articles.articles', verbose_name='Artículo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replicas', to='comments.comment', verbose_name='Comentario padre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentarios', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_comentarios', to='comments.comment', verbose_name='Comentario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_comentarios', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Me gusta en comentario',
                'verbose_name_plural': 'Me gusta en comentarios',
                'db_table': 'comment_likes',
                'unique_together': {('user', 'comment')},
            },
        ),
    ]
