# Generated by Django 5.2.1 on 2025-06-14 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_maternal_surname_remove_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.rol', verbose_name='Rol'),
        ),
        migrations.DeleteModel(
            name='UserRol',
        ),
    ]
