# Generated by Django 5.2.1 on 2025-06-01 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='Category Slug')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'articles_category',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Nombre de la Etiqueta')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Título del Artículo')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug del Artículo')),
                ('content', models.TextField(blank=True, verbose_name='Contenido del Artículo')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción del Artículo')),
                ('thumbnail_image', models.ImageField(blank=True, upload_to='articles/thumbnails/', verbose_name='Imagen en miniatura del Artículo')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Archivado')], default='draft', max_length=10, verbose_name='Estado del Artículo')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Publicación')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vistas del Artículo')),
                ('shares_count', models.PositiveIntegerField(default=0, verbose_name='Compartidos del Artículo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Autor del Artículo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='articles.articlescategory', verbose_name='Categoría del Artículo')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'db_table': 'articles',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticlesFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='articles.articles', verbose_name='Artículo marcado como favorito')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_articles', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que marcó como favorito')),
            ],
            options={
                'verbose_name': 'Artículo Favorito',
                'verbose_name_plural': 'Artículos Favoritos',
                'db_table': 'articles_favorites',
                'unique_together': {('user', 'article')},
            },
        ),
        migrations.CreateModel(
            name='ArticlesLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='articles.articles', verbose_name='Artículo al que se le dio like')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_articles', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que dio like')),
            ],
            options={
                'verbose_name': 'Like de Artículo',
                'verbose_name_plural': 'Likes de Artículos',
                'db_table': 'articles_likes',
                'unique_together': {('user', 'article')},
            },
        ),
        migrations.CreateModel(
            name='ArticlesTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='articles.articles', verbose_name='Artículo')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.tags', verbose_name='Etiqueta')),
            ],
            options={
                'verbose_name': 'Artículo Etiqueta',
                'verbose_name_plural': 'Artículos Etiquetas',
                'db_table': 'articles_tags',
                'unique_together': {('article', 'tag')},
            },
        ),
    ]
