# Generated by Django 5.2.1 on 2025-07-29 05:00

import articles.models.articles
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='thumbnail_image',
            field=models.ImageField(blank=True, upload_to=articles.models.articles.article_thumbnail_upload_to, verbose_name='Imagen en miniatura del Artículo'),
        ),
    ]
