# Generated by Django 5.2.1 on 2025-08-03 23:02

import articles.models.articles_category
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articles_thumbnail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlescategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=articles.models.articles_category.image_upload_to, verbose_name='Category Image'),
        ),
    ]
