# Generated by Django 5.2.1 on 2025-08-04 08:20

import articles.models.articles_category
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articlescategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlescategory',
            name='image',
            field=models.ImageField(default='vexon/img/logo/article_default.webp', upload_to=articles.models.articles_category.image_upload_to, verbose_name='Category Image'),
        ),
    ]
