# Generated by Django 5.2.1 on 2025-08-04 08:51

import articles.models.articles
import articles.models.articles_category
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_articlescategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='thumbnail_image',
            field=models.ImageField(default='vexon/img/logo/article_default.webp', upload_to=articles.models.articles.article_thumbnail_upload_to, verbose_name='Imagen en miniatura del Artículo'),
        ),
        migrations.AlterField(
            model_name='articlescategory',
            name='image',
            field=models.ImageField(default='vexon/img/logo/category_default.webp', upload_to=articles.models.articles_category.image_upload_to, verbose_name='Category Image'),
        ),
    ]
