# Generated by Django 5.2.1 on 2025-06-01 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Nombre del modelo')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID del objeto')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10, verbose_name='Acción realizada')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción de la acción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de actualización')),
                ('audit_version', models.PositiveIntegerField(default=1, verbose_name='Versión de auditoría')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objetos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que creó el objeto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='objetos_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que actualizó el objeto')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'ordering': ['model', '-created_at', '-updated_at'],
            },
        ),
    ]
